<a href="https://colab.research.google.com/github/Paalak-Agrawal/NumPy-Practice-Notebook/blob/main/NumPy_Practice_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ============================================================
# ASSIGNMENT: NUMPY PRACTICE NOTEBOOK (DAY 6)
# ============================================================

import numpy as np

print("NumPy imported successfully!")


# ============================================================
# 1. CREATING 1D, 2D, AND 3D ARRAYS
# ============================================================

print("\n--- 1D ARRAY ---")
array_1d = np.array([10, 20, 30, 40, 50])
print(array_1d)

print("\n--- 2D ARRAY ---")
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(array_2d)

print("\n--- 3D ARRAY ---")
array_3d = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])
print(array_3d)


# ============================================================
# 2. CHECKING DIMENSIONS, DATA TYPE, SHAPE, AND SIZE
# ============================================================

print("\n--- ARRAY INFORMATION ---")

print("1D Array Dimensions:", array_1d.ndim)
print("2D Array Dimensions:", array_2d.ndim)
print("3D Array Dimensions:", array_3d.ndim)

print("\nData Type of 1D Array:", array_1d.dtype)
print("Shape of 2D Array:", array_2d.shape)
print("Size of 3D Array:", array_3d.size)


# ============================================================
# 3. INDEXING
# ============================================================

print("\n--- INDEXING ---")

array = np.array([10, 20, 30, 40, 50])

print("Array:", array)
print("First element:", array[0])
print("Third element:", array[2])
print("Last element:", array[-1])


# ============================================================
# 4. 2D ARRAY INDEXING
# ============================================================

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("\n2D Array:")
print(matrix)

print("Element at row 1, column 2:", matrix[0, 1])
print("Element at row 3, column 1:", matrix[2, 0])


# ============================================================
# 5. SLICING
# ============================================================

print("\n--- 1D ARRAY SLICING ---")

array = np.array([10, 20, 30, 40, 50, 60])

print("Original Array:", array)
print("Elements from index 1 to 4:", array[1:5])
print("First three elements:", array[:3])
print("Elements from index 3 onwards:", array[3:])


# ============================================================
# 6. 2D ARRAY SLICING
# ============================================================

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("\n--- 2D ARRAY SLICING ---")

print("Original Matrix:")
print(matrix)

print("\nFirst two rows:")
print(matrix[:2])

print("\nFirst two columns:")
print(matrix[:, :2])


# ============================================================
# 7. RESHAPING ARRAYS
# ============================================================

print("\n--- RESHAPING ARRAYS ---")

array = np.arange(1, 13)

print("Original Array:")
print(array)

reshaped_array = array.reshape(3, 4)

print("\nReshaped Array (3 x 4):")
print(reshaped_array)


# ============================================================
# 8. CREATING ARRAYS USING NUMPY FUNCTIONS
# ============================================================

print("\n--- ZEROS ARRAY ---")
zeros_array = np.zeros((2, 3))
print(zeros_array)

print("\n--- ONES ARRAY ---")
ones_array = np.ones((3, 2))
print(ones_array)

print("\n--- ARANGE ARRAY ---")
arange_array = np.arange(0, 10, 2)
print(arange_array)

print("\n--- LINSPACE ARRAY ---")
linspace_array = np.linspace(0, 10, 5)
print(linspace_array)


# ============================================================
# 9. MATHEMATICAL OPERATIONS
# ============================================================

print("\n--- MATHEMATICAL OPERATIONS ---")

array = np.array([1, 2, 3, 4, 5])

print("Original Array:", array)
print("Addition:", array + 10)
print("Subtraction:", array - 2)
print("Multiplication:", array * 2)
print("Division:", array / 2)
print("Square:", array ** 2)


# ============================================================
# 10. VECTORIZED OPERATIONS
# ============================================================

print("\n--- VECTORIZED OPERATIONS ---")

array1 = np.array([1, 2, 3, 4])
array2 = np.array([10, 20, 30, 40])

print("Array 1:", array1)
print("Array 2:", array2)

print("Addition:", array1 + array2)
print("Subtraction:", array1 - array2)
print("Multiplication:", array1 * array2)
print("Division:", array2 / array1)


# ============================================================
# 11. BOOLEAN MASKING
# ============================================================

print("\n--- BOOLEAN MASKING ---")

marks = np.array([45, 78, 32, 90, 65, 28, 85])

passed_students = marks[marks >= 40]

print("All Marks:", marks)
print("Marks of Passed Students:", passed_students)


numbers = np.array([10, 15, 20, 25, 30])

print("\nNumbers:", numbers)
print("Numbers greater than 20:")
print(numbers[numbers > 20])


# ============================================================
# 12. BROADCASTING
# ============================================================

print("\n--- BROADCASTING ---")

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

number = 10

result = matrix + number

print("Original Matrix:")
print(matrix)

print("\nMatrix after adding 10:")
print(result)


print("\n--- BROADCASTING WITH TWO ARRAYS ---")

values = np.array([10, 20, 30])

result = matrix + values

print(result)


# ============================================================
# 13. AGGREGATE FUNCTIONS
# ============================================================

print("\n--- AGGREGATE FUNCTIONS ---")

numbers = np.array([10, 20, 30, 40, 50])

print("Array:", numbers)

print("Sum:", np.sum(numbers))
print("Mean:", np.mean(numbers))
print("Minimum:", np.min(numbers))
print("Maximum:", np.max(numbers))
print("Median:", np.median(numbers))


# ============================================================
# 14. AGGREGATE FUNCTIONS ON 2D ARRAY
# ============================================================

print("\n--- AGGREGATE FUNCTIONS ON 2D ARRAY ---")

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Matrix:")
print(matrix)

print("\nTotal Sum:", np.sum(matrix))
print("Overall Mean:", np.mean(matrix))

print("\nSum of each column:")
print(np.sum(matrix, axis=0))

print("\nSum of each row:")
print(np.sum(matrix, axis=1))


# ============================================================
# 15. STUDENT MARKS ANALYSIS
# ============================================================

print("\n--- STUDENT MARKS ANALYSIS ---")

student_marks = np.array([78, 85, 92, 65, 70, 88, 95, 55])

print("Student Marks:")
print(student_marks)

print("\nTotal Marks:", np.sum(student_marks))
print("Average Marks:", np.mean(student_marks))
print("Highest Marks:", np.max(student_marks))
print("Lowest Marks:", np.min(student_marks))
print("Median Marks:", np.median(student_marks))

passed = student_marks[student_marks >= 40]

print("\nPassed Student Marks:")
print(passed)

print("Number of Passed Students:", len(passed))


# ============================================================
# END OF PROGRAM
# ============================================================

print("\nNumPy Practice Notebook completed successfully!")

NumPy imported successfully!

--- 1D ARRAY ---
[10 20 30 40 50]

--- 2D ARRAY ---
[[1 2 3]
 [4 5 6]]

--- 3D ARRAY ---
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

--- ARRAY INFORMATION ---
1D Array Dimensions: 1
2D Array Dimensions: 2
3D Array Dimensions: 3

Data Type of 1D Array: int64
Shape of 2D Array: (2, 3)
Size of 3D Array: 8

--- INDEXING ---
Array: [10 20 30 40 50]
First element: 10
Third element: 30
Last element: 50

2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at row 1, column 2: 20
Element at row 3, column 1: 70

--- 1D ARRAY SLICING ---
Original Array: [10 20 30 40 50 60]
Elements from index 1 to 4: [20 30 40 50]
First three elements: [10 20 30]
Elements from index 3 onwards: [40 50 60]

--- 2D ARRAY SLICING ---
Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

First two rows:
[[1 2 3]
 [4 5 6]]

First two columns:
[[1 2]
 [4 5]
 [7 8]]

--- RESHAPING ARRAYS ---
Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped Array (3 x 4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 